# Dependencies
markdown:            redcarpet
highlighter:         pygments

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Roman Piták
tagline:             blog
description:         'A blog of code and the human nature.'
url:                 http://blog.pitak.net
baseurl:             ''
paginate:            5
disqus_shortname:    pitak

# About/contact
author:
  name:              Roman Piták
  url:               http://pitak.net
  email:             roman@pitak.net

# Custom vars
